In [33]:
import numpy as np
from scipy import linalg as la

# create some matrices

b = np.array([(1 + 5j, 2j, 3j), (4j, 5j, 6j)])

b

array([[ 1.+5.j,  0.+2.j,  0.+3.j],
       [ 0.+4.j,  0.+5.j,  0.+6.j]])

In [34]:
A = np.matrix(np.random.random((2,2)))
A

matrix([[ 0.70504105,  0.3321162 ],
        [ 0.02779544,  0.94304591]])

In [35]:
B = np.asmatrix(b)
B

matrix([[ 1.+5.j,  0.+2.j,  0.+3.j],
        [ 0.+4.j,  0.+5.j,  0.+6.j]])

In [36]:
C = np.mat(np.random.random((10,5)))
C

matrix([[ 0.87936613,  0.05867248,  0.42004751,  0.13896262,  0.54486258],
        [ 0.1050803 ,  0.70013377,  0.46983602,  0.45597053,  0.83908597],
        [ 0.07387426,  0.36678777,  0.42322492,  0.58670458,  0.21765784],
        [ 0.97553625,  0.23627734,  0.21666947,  0.93652425,  0.91117443],
        [ 0.82196407,  0.90060572,  0.18610818,  0.45974763,  0.4410616 ],
        [ 0.97335276,  0.695081  ,  0.70382352,  0.72248857,  0.03892971],
        [ 0.49620205,  0.76949687,  0.0365875 ,  0.86096212,  0.60605155],
        [ 0.05156688,  0.61858866,  0.27759148,  0.81962994,  0.65278432],
        [ 0.65768715,  0.29308599,  0.14190364,  0.93966058,  0.00134654],
        [ 0.09872958,  0.25133338,  0.33315747,  0.93565295,  0.13031809]])

In [37]:
D = np.mat([[3, 4], [5, 6]])
D

matrix([[3, 4],
        [5, 6]])

In [38]:
# matrix inverse
A.I

matrix([[ 1.43832695, -0.50654128],
        [-0.0423934 ,  1.07532361]])

In [39]:
# transpose
A.transpose()

matrix([[ 0.70504105,  0.02779544],
        [ 0.3321162 ,  0.94304591]])

In [40]:
A

matrix([[ 0.70504105,  0.3321162 ],
        [ 0.02779544,  0.94304591]])

In [41]:
# trace
A.trace()

matrix([[ 1.64808696]])

In [42]:
# norm
la.norm(A)

1.2237206504302973

In [43]:
la.norm(A,1)

1.2751621163209719

In [44]:
la.norm(A, np.inf)

1.0371572494551877

In [45]:
# rank
np.linalg.matrix_rank(C)

5

In [46]:
# determinant
la.det(A)

0.6556547624508648

In [47]:
# solve linear problems 
la.solve(A, b)

array([[ 1.43832695+5.16546962j,  0.00000000+0.34394749j,
         0.00000000+1.27573316j],
       [-0.04239340+4.08932742j,  0.00000000+5.29183124j,
         0.00000000+6.32476145j]])

In [48]:
# matrix addition
np.add(A, D)

matrix([[ 3.70504105,  4.3321162 ],
        [ 5.02779544,  6.94304591]])

In [49]:
# matrix subtraction
np.subtract(A, D)

matrix([[-2.29495895, -3.6678838 ],
        [-4.97220456, -5.05695409]])

In [50]:
# matrix division
np.divide(A, D)

matrix([[ 0.23501368,  0.08302905],
        [ 0.00555909,  0.15717432]])

In [51]:
np.multiply(A, D)

matrix([[ 2.11512314,  1.32846481],
        [ 0.13897719,  5.65827548]])

In [52]:
np.dot(A, D)

matrix([[ 3.77570415,  4.8128614 ],
        [ 4.79861588,  5.76945723]])

In [53]:
la.expm(A)

array([[ 2.03406685,  0.76008037],
       [ 0.06361257,  2.57876424]])

In [54]:
# eigen values and vectors
val, vec = la.eig(A)

In [55]:
val

array([ 0.67109612+0.j,  0.97699084+0.j])

In [56]:
vec

array([[-0.99481734, -0.77370794],
       [ 0.10167826, -0.63354245]])

In [57]:
# singular value decomposition

In [59]:
U, s, Vh = la.svd(D)

In [60]:
U

array([[-0.53895353, -0.8423355 ],
       [-0.8423355 ,  0.53895353]])

In [61]:
s

array([ 9.27110906,  0.21572392])

In [62]:
Vh

array([[-0.62867755, -0.77766609],
       [ 0.77766609, -0.62867755]])

In [63]:
M, N = D.shape

In [64]:
M

2

In [65]:
N

2

In [66]:
Sig = la.diagsvd(s, M, N)
Sig

array([[ 9.27110906,  0.        ],
       [ 0.        ,  0.21572392]])