In [2]:
import numpy as np

# create some vector

A = np.array([1, 2])

In [3]:
A

array([1, 2])

In [4]:
B = np.array([2, 1])

In [5]:
B

array([2, 1])

In [6]:
A + B

array([3, 3])

In [7]:
3 * A

array([3, 6])

In [8]:
np.dot(A, B)

4

In [9]:
A * B

array([2, 2])

In [10]:
C = np.array([0, 1])
D = np.array([1, 0])

dot_p = np.dot(C, D)

dot_p

0

In [11]:
if dot_p == 0:
    print("The vectors " + str(C) + " and " + str(D) + " are orthonogal.")
else:
    print("No orthogonality detected.")

The vectors [0 1] and [1 0] are orthonogal.
